### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by chepkok3** [chepkok3/Personal-Portfolio#11]
https://chepkok3.github.io/Personal-Portfolio/

**Comment by TuyishimireEric** [comment]
# Status: APPROVED 🟢  
### Hi  @chepkok3      👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️The project is deployed 👍 
### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
